# Generated by Django 3.2 on 2023-06-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='report_cnt',
        ),
    ]
